#pragma once
#include "Vertex.h"
#include "FVF.h"
class IMPORTEXPORT Mesh
{
	LPDIRECT3DVERTEXBUFFER9 vb;
	LPDIRECT3DINDEXBUFFER9 ind;
public:
	Mesh(LPDIRECT3DDEVICE9 dev);
	~Mesh();
	LPDIRECT3DVERTEXBUFFER9 GetVb();
	LPDIRECT3DINDEXBUFFER9 GetInd();
};

