#pragma once
#include "Vertex.h"
#define CUSTOMFVF (D3DFVF_XYZ| D3DFVF_DIFFUSE)
class IMPORTEXPORT Mesh
{
	LPDIRECT3DVERTEXBUFFER9 vb;
	LPDIRECT3DINDEXBUFFER9 ind;
public:
	Mesh(LPDIRECT3DDEVICE9 dev);
	~Mesh();
	LPDIRECT3DVERTEXBUFFER9 GetVb();
	LPDIRECT3DINDEXBUFFER9 GetInd();
};

